### PR TITLE
Added comments in source code and corrected syntax in css code

### PR DESCRIPTION
**Pull request by ronitsingh1405**
# Description & Fixes
I have added comments in index.html code and corrected a syntax of about.css code.
Issue #22 

# How Has This Been Tested?
I have ran it and tested it on my chrome browser. Worked perfectly fine.

### CODE REVIEW

**Comment by vinayaksh42** [comment]
Great work bro

**Comment by ronitsingh1405** [comment]
Shall I do so with other html and css files too?

**Comment by vinayaksh42** [comment]
yes if it is convenient for you to do so @ronitsingh1405

**Comment by ronitsingh1405** [comment]
Oh that's great! I am ready!

**Pull request merged**
